
ALTER TABLE public.machine_readings
  ADD COLUMN debit_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN credit_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN voucher_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN pix_count INTEGER NOT NULL DEFAULT 0;
